apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: TEST  # Initialize with TEST database
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
    - port: 27017
  selector:
    app: mongodb
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: leader-election-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: leader-election
  template:
    metadata:
      labels:
        app: leader-election
    spec:
      containers:
        - name: leader-election
          image: kamruddin/leader-election:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb:27017/TEST
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: leader-election-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: leader-election
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007