apiVersion: v1
kind: ConfigMap
metadata:
  name: leader
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-election-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: leader-election-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leader-election-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: leader-election
  template:
    metadata:
      labels:
        app: leader-election
    spec:
      containers:
        - name: leader-election
          image: kamruddin/leader-election:latest
          ports:
            - containerPort: 8080
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: leader-election-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: leader-election
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007

